apiVersion: v1
kind: PersistentVolume
metadata:
 name: aero-nfs-pv
spec:
 capacity:
   storage: 10Gi
 accessModes:
 - ReadWriteMany
 nfs:
   path: /vol1/
   server: 10.66.156.58 # Filestore IP Address to persistent Volume